apiVersion: v2
name: my-app
description: A Helm chart for deploying my-app to Kubernetes
type: application

# Helm chart version (MUST bump on every push)
version: 0.4.0

# Application version (Docker image version)
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/helm/helm/main/docs/logos/helm.png


keywords:
  - my-app
  - kubernetes
  - helm
  - uat
  - prod

home: https://github.com/ananddonepudi/my-app
sources:
  - https://github.com/ananddonepudi/my-app

maintainers:
  - name: Anand
    email: ananddonepudi@gmail.com

annotations:
  category: application
