apiVersion: v2
name: my-app
description: A Helm chart for deploying my-app to Kubernetes
type: application

# Helm chart version (MUST bump on every push)
version: 0.1.0

# Application version (Docker image version)
appVersion: "1.0.0"

keywords:
  - my-app
  - kubernetes
  - helm
  - uat
  - prod

home: https://github.com/your-org/my-app
sources:
  - https://github.com/your-org/my-app

maintainers:
  - name: Anand
    email: ananddonepudi@gmail.com

annotations:
  category: application
